### ISSUE TITLE
java.lang.NullPointerException: ssl == null

### ISSUE THREAD

**Issue by oleonov** [centrifugal/centrifuge-android#14]
I have exception
`FATAL EXCEPTION: Centrifugo
Process: pro.myburse.app, PID: 27180
java.lang.NullPointerException: ssl == null
 at com.android.org.conscrypt.NativeCrypto.SSL_set_timeout(Native Method)
 at com.android.org.conscrypt.SslWrapper.setTimeout(SslWrapper.java:101)
 at com.android.org.conscrypt.ActiveSession.invalidate(ActiveSession.java:147)
 at com.android.org.conscrypt.DelegatingExtendedSSLSession.invalidate(DelegatingExtendedSSLSession.java:120)
 at org.java_websocket.SSLSocketChannel2.close(SSLSocketChannel2.java:268)
 at org.java_websocket.WebSocketImpl.closeConnection(WebSocketImpl.java:453)
 at org.java_websocket.WebSocketImpl.eot(WebSocketImpl.java:511)
 at org.java_websocket.client.WebSocketClient.interruptableRun(WebSocketClient.java:249)
 at org.java_websocket.client.WebSocketClient.run(WebSocketClient.java:188)
 at java.lang.Thread.run(Thread.java:764)
`
on `centrifugo.disconnect()`
Probke is not only in exception - I can't catch it

**Comment by FZambia** [comment]
@oleonov hello, thanks for report! Currently I am looking for maintainer for this library.
